### ISSUE TITLE
vsgshadow has black patches flickering on the ground

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/vsgExamples#273] opened 2023-10-17 00:47 UTC
Hi,
I run vsgshadow on Windows 11,most of the time, it seems fine,but sometimes there are black patches flickering on the shadow receiving surface.using --debug console output none information.I have carefully studied the pre RenderCommandGraph (submitOrder=-1) code, but I do not know how to ensure that the shadow RTT is rendered before being used by subsequent CommandGraph (submitOrder=0)
<img width="640" alt="2" src="https://github.com/vsg-dev/vsgExamples/assets/75113990/34564cdd-537f-4aea-bfd2-c9e9a3fff436">
<img width="640" alt="3" src="https://github.com/vsg-dev/vsgExamples/assets/75113990/f62826dc-a94d-4281-a778-3cf7ec88836c">

**Comment by robertosfield** [comment] 2023-10-17 06:53
I haven't seen issue like this before so I can only guess that it's something related to the hardware/drivers.  What hardware and drivers are you using?

Could you try setting the shadow map  bias so a higher value to see if it's depth precision issue.  I wrote up about this on the Discussion thread about the shadow map work.

The render order of the shadow map is controlled by nested CommandGrsph support that I introduced last month, just setting the submit order to -1 will ensure that the associated command buffer gets submitted before any CommandGraph with 0 or greater submit value.

**Comment by robertosfield** [comment] 2023-11-22 18:09
As a follow up, I have fixed a bug in the TransferTask/RecordAndSubmitTasks that caused problems on NVidia cards when a separate transfer queue was used to transfer the light and shadowmap data to the GPU, this resulted in odd out of sync shadows that was visible when the camera position moved rapidly.  

The fix was merged with the PR:
https://github.com/vsg-dev/VulkanSceneGraph/pull/1033

 @simwangrui  Could you test  VSG and vsgExamples master to see how things are behaving now.  If the problem persists then please let us know what hardware and drivers you are working with so we can see if others in the community can reproduce the problem.

**Comment by simwangrui** [comment] 2023-11-24 02:06
Hi，
Sorry, it took too long before I could access github. I pulled the latest master branch code of VulkanSceneGraph, compiled and ran vsgshadow, and it is now running perfectly. My system is Windows 11, the graphics card is Nvidia RTX A4500 ada, and the driver version is R535 U6 (537.42). Thank you for solving this issue.

**Comment by robertosfield** [comment] 2023-11-24 07:52
Thanks for the testing, good to hear the problem is solved.

**Closed by robertosfield** 2023-11-24 07:52 UTC
