### ISSUE TITLE
vsgstatecomposer crashes on MacOS and Windows10

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgExamples#146] opened 2022-05-04 09:46 UTC
Hi Robert,

after pulling the actual commits a problem occurs with the vsgstatecomposer example on the Mac and on my Windows machine as well:

Mac:
[mac_error.txt](https://github.com/vsg-dev/vsgExamples/files/8619213/mac_error.txt)

Windows:
[win_error.txt](https://github.com/vsg-dev/vsgExamples/files/8619221/win_error.txt)

Vulkan version 1.3.211.0 ist used on both systems.

**Comment by robertosfield** [comment] 2022-05-04 09:58
Oopps... I'm getting a crash under Linux as well.  I did test it not long before merging with master, but can't remember the exact combination of settings I was using so I don't know off the top of my head what might be the cause of the problem.

I'm in the middle of figuring out how to implement vsg::Path's, once that's wrapped up I'll investigate. 

$ vsgstatecomposer -d
centre = 0 0 -0.25
radius = 2.7
VUID-VkGraphicsPipelineCreateInfo-layout-00756(ERROR / SPEC): msgNum: 1165064310 - Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-00756 ] Object 0: handle = 0x55cf2904c730, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x45717876 | Shader uses descriptor slot 1.0 (expected `VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK`) but not declared in pipeline layout The Vulkan spec states: layout must be consistent with all shaders specified in pStages (https://vulkan.lunarg.com/doc/view/1.3.204.1/linux/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-00756)
    Objects: 1
        [0] 0x55cf2904c730, type: 3, name: NULL
Segmentation fault (core dumped)

**Comment by robertosfield** [comment] 2022-05-12 13:43
I have tracked down the regression to the phong and pbr ShaderSet being simplified to just supporting the ViewDependentState codepaths, so now require the setup of vsg::ViewDepenentState.  The fix is checked into vsgExamples master: b57d2937a1a4c03a30f9c0b374132e7116fd2a4e

**Closed by robertosfield** 2022-05-12 13:43 UTC
