### ISSUE TITLE
Black canvas while running raytracing example

### ISSUE THREAD

**Issue by olegded** [vsg-dev/vsgExamples#67] opened 2020-11-01 11:12 UTC
System:
- Ubuntu - 20.04, VulkanSDK - 1.2.148.0

1. Checkout and compile latest `vsg`, `vsgXchange` and `vsgExamples` versions
2. Start `raytracing` sample

Result:
- Black canvas while rendering. There are following error messages in the console:

First one is about wrong size of `missShaderBindingOffset` after very first call to `extensions->vkCmdTraceRaysNV()`
![vsg_rt_6](https://user-images.githubusercontent.com/6074172/97801049-410d3e80-1c3a-11eb-937f-63503afb056e.jpg)

Second one is about wrong image layout after first call to `RecordAndSubmitTask::finish()` followed by `Queue::submit()`
![vsg_rt_8](https://user-images.githubusercontent.com/6074172/97801030-1622ea80-1c3a-11eb-894a-2b6a166b3daa.jpg)

After that, the console is overflowed with the first error message, the second one seems to occur only once.

Oleg

**Comment by robertosfield** [comment] 2020-11-01 13:05
Hi Oleg,

What hardware are you using?  You'll need NVidia RTX hardware.

My current multiple GPU system doesn't support ray tracing so I haven't
been able to test for a while, so a regression may be slipped in.  Perhaps
it's time for swap back in my Gefore 2060 RTX card.

**Comment by olegded** [comment] 2020-11-01 14:51
Hi Robert,

Yes, sure, I have GeForce RTX 2060 card. This sample was working for me, my last checkouted version was one prior to the text-related changes, so an "old" one. I checked the latest version today and noticed it.

Oleg

**Comment by robertosfield** [comment] 2020-11-01 19:58
Hi Oleg,

On Sun, 1 Nov 2020 at 14:51, olegded <notifications@github.com> wrote:

> Yes, sure, I have GeForce RTX 2060 card. This sample was working for me,
> my last checkouted version was one prior to the text-related changes, so an
> "old" one. I checked the latest version today and noticed it.
>
Thanks for the detail, that provides a bit better constraint on where the
regression has occurred.

I'll pop my 2060 back in later this week and have a look.  If you can't
wait for me to get to it then a good way to track down regressions is to
use the Vulkan api debug layer (use -a command line option to enable it)
and record the output to file on the version that works, then update to the
broken version and run the same test and record the api output to a file.

To make it easier to compare the good and result results it's useful to run
the PointerMap utility that I wrote earlier in the year.

Cheers,
Robert.

**Comment by olegded** [comment] 2020-11-02 07:57
I will try but this is not urgent at all :-)

Oleg

**Comment by robertosfield** [comment] 2020-11-13 15:26
I've not put my Geforce2060 back in and am looking into the vsgraytracing regression.  I see a blue screen the same debug layer errors.

**Comment by robertosfield** [comment] 2020-11-14 17:15
I have resolved alignment part of the ray tracing problems with this commit to the VSG RaytracingFix branch:

    https://github.com/vsg-dev/VulkanSceneGraph/commit/f6488968752f314e88656d52ace54ecdefaef9ad

Rather than getting a black window I now get an odd/random pixelated window so clearly still some way to go.

I haven't yet got to the bottom of the vkImage related debug error, so this might be the cause of the errors on screen I still see:

$ vsgraytracing -d 
UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout(ERROR / SPEC): msgNum: 1303270965 - Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x562485e76600, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buffer expects VkImage 0x40000000004[] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.
    Objects: 1
        [0] 0x562485e76600, type: 6, name: NULL

**Comment by robertosfield** [comment] 2020-11-17 16:00
It's took me two and half days to track down the cause of the regression, finally homed into the cause this afternoon and checked in a fix to VSG master:

    https://github.com/vsg-dev/VulkanSceneGraph/commit/53db01ec7f30981570194ec9531be08750f0970b

**Closed by robertosfield** 2020-11-17 16:00 UTC
